exclude_paths:
  - '**.DS_Store'
  - '**.test.js'
  - '**.stories.js'
  - '**.json'
  - 'src/components/common/PageExamples/**'
  - 'node_modules/**'
  - '.storybook/**'
  - 'docs/**'
  - 'environment/**'
  - 'protocol/**'
  - 'rest/vendor/**'
  - 'rest/tests/**'
  - 'rest/database/migrations/**'