<?php

namespace App\Models\Traits;

use App\Models\ContractStatusDetail;

trait DisputeTrait
{
    public function getLastPart()
    {
        $last = $this->details->sortByDesc('id')->first();

        return $last->contract_part;
    }

    public function getTokensPart($part)
    {
        $part = $this->{$part};
        $totalPart = $this->votes->where('wallet_part', $part)->sum('amount');

        return $totalPart;
    }

    public function getEarnings()
    {
        if ($this->status->code =! 39) {
            return null;
        }

        $totalPartA = $this->getTokensPart('part_a_wallet');
        $totalPartB = $this->getTokensPart('part_b_wallet');
        $voteForWinner = 0;
        if ($totalPartA > $totalPartB) {
            $voteForWinner = $this->votes->where('wallet_part', $this->part_a_wallet)->count();
        } elseif ($totalPartB > $totalPartA) {
             $voteForWinner = $this->votes->where('wallet_part', $this->part_b_wallet)->count();
        }

        if ($voteForWinner > 0) {
            return ($totalPartA + $totalPartB) / $voteForWinner;
        }
        return null;
    }

    public function getProposalPart($part)
    {
        $partFields = "{$part}_wallet";
        $detail = $this->details->where('contract_part', $this->{$partFields})->first();

        if ($detail) {
            $evidences = [];
            foreach ($detail->getMedia('evidences') as $evidence) {
                $evidences[] = [
                    'id' => $evidence->id,
                    'fileName' => $evidence->file_name,
                    'url' => $evidence->getFullUrl()
                ];
            }

            return [
                'date' => $detail->created_at->valueOf(),
                'message' => $detail->message,
                'proposal' => (object) [
                    'proposal_part_a' => $detail->proposal_part_a,
                    'proposal_part_b' => $detail->proposal_part_b
                ],
                'payed_at' => $detail->payed_at ? $detail->payed_at->valueOf() : null,
                'evidences' => $evidences
            ];
        }

        return $detail;
    }

    /**
     * Check if the activities has been generated by the system.
     *
     * @return boolean
     */
    protected function getSystem(ContractStatusDetail $detail)
    {
        $status = $detail->contract->status;
        if (in_array($status->code, [39,8])) {
            return true;
        }
        return false;
    }
}
