// App
export const APP_REFRESH = "APP_REFRESH";
export const SET_READY = "SET_READY";
export const SET_LOADING = "SET_LOADING";
export const RESET_APP_STATE = "RESET_APP_STATE";

export const SET_TUTORIAL_VIEWED = "SET_TUTORIAL_VIEWED";
export const APP_SHOULD_RESET = "APP_SHOULD_RESET";
export const APP_EXIT = "APP_EXIT";
export const HEARTBEAT = "HEARTBEAT";

// User
export const DISCLAIMER_OPTIN = "DISCLAIMER_OPTIN";
export const RESET_USER = "RESET_USER";

// Wallet
export const SET_BALANCE = "SET_BALANCE";
export const SET_WALLET_ADDRESS = "SET_WALLET_ADDRESS";
export const RESET_WALLET = "RESET_WALLET";

// Contracts
export const DELETE_ALL_CONTRACTS = "DELETE_ALL_CONTRACTS";
export const DELETE_ALL_DISPUTES = "DELETE_ALL_DISPUTES";

// Drizzle
export const DRIZZLE_INITIALIZING = "DRIZZLE_INITIALIZING";
export const DRIZZLE_INITIALIZED = "DRIZZLE_INITIALIZED";
export const ACCOUNTS_FETCHED = "ACCOUNTS_FETCHED";
export const CONTRACT_INITIALIZED = "CONTRACT_INITIALIZED";
export const NETWORK_ID_FAILED = "NETWORK_ID_FAILED";
export const GOT_CONTRACT_VAR = "GOT_CONTRACT_VAR";

// NETWORK
export const NETWORK_UPDATE = "NETWORK_UPDATE";

// ARBITRATION
export const NEW_ARBITRATION = "NEW_ARBITRATION";