// App
export const APP_REFRESH = "APP_REFRESH";
export const SET_READY = "SET_READY";
export const SET_LOADING = "SET_LOADING";
export const RESET_APP_STATE = "RESET_APP_STATE";

export const SET_TUTORIAL_VIEWED = "SET_TUTORIAL_VIEWED";
export const APP_SHOULD_RESET = "APP_SHOULD_RESET";
export const APP_EXIT = "APP_EXIT";
export const HEARTBEAT = "HEARTBEAT";

export const API_CATCH = "API_CATCH";
export const FETCH_FAQ = "FETCH_FAQ";
export const SET_FAQ = "SET_FAQ";

// User
export const DISCLAIMER_OPTIN = "DISCLAIMER_OPTIN";
export const DISCLAIMER_VISIBILITY = "DISCLAIMER_VISIBILITY";
export const DISCLAIMER_ACCEPTED = "DISCLAIMER_ACCEPTED";
export const DISCLAIMER_MUST_BE_ACCEPTED = "DISCLAIMER_MUST_BE_ACCEPTED";
export const NEW_USER = "NEW_USER";
export const FETCH_USER = "FETCH_USER";
export const USER_UPDATE = "USER_UPDATE";
export const USER_OBLIVION = "USER_OBLIVION";
export const RESET_USER = "RESET_USER";
export const UPDATE_USER_FIELD = "UPDATE_USER_FIELD";
export const PUT_USER = "PUT_USER";
export const USER_UPDATING = "USER_UPDATING";

// Wallet
export const SET_BALANCE = "SET_BALANCE";
export const SET_WALLET_ADDRESS = "SET_WALLET_ADDRESS";
export const RESET_WALLET = "RESET_WALLET";

// Contracts
export const DELETE_ALL_CONTRACTS = "DELETE_ALL_CONTRACTS";
export const DELETE_ALL_DISPUTES = "DELETE_ALL_DISPUTES";

export const NEW_CONTRACT = "NEW_CONTRACT";
export const UPDATE_CONTRACT_FIELD = "UPDATE_CONTRACT_FIELD";
export const PUT_CONTRACT = "PUT_CONTRACT";
export const RESET_CONTRACT = "RESET_CONTRACT";

// Drizzle
export const DRIZZLE_INITIALIZING = "DRIZZLE_INITIALIZING";
export const DRIZZLE_INITIALIZED = "DRIZZLE_INITIALIZED";
export const ACCOUNTS_FETCHED = "ACCOUNTS_FETCHED";
export const CONTRACT_INITIALIZED = "CONTRACT_INITIALIZED";
export const NETWORK_ID_FAILED = "NETWORK_ID_FAILED";
export const GOT_CONTRACT_VAR = "GOT_CONTRACT_VAR";

// NETWORK
export const NETWORK_UPDATE = "NETWORK_UPDATE";

// ARBITRATION
export const NEW_ARBITRATION = "NEW_ARBITRATION";